name: Check for API changes

on: [push, pull_request]

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run API-Extractor
        run: yarn api:check
      - name: API-Extractor failure
        if: ${{ failure() }}
        uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: packages/charts/api/charts.api.md
          new: packages/charts/tmp/charts.api.md
          mode: deletion
          tolerance: better
