name: Unit testing

on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@HEAD
      - name: TimeZone testing
        run: yarn test:tz --ci
      - name: Testing
        run: yarn test --coverage --ci
#      - uses: codecov/codecov-action@v1
#        with:
#          flags: unittests # optional
#          name: gha # optional
#          fail_ci_if_error: false
