language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn build && yarn lint && yarn test
after_success:
  - yarn semantic-release
before_deploy: yarn storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target-branch: gh-pages
  keep-history: false # always force push
  local_dir: .out
