language: node_js
cache: yarn
# nodejs version from nvmrc
# yarn install is default install lifecycle
script: yarn build:ts --noEmit && yarn lint && yarn test
# skipping this to check the deploy
after_success: yarn semantic-release
before_deploy: yarn storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target-branch: gh-pages
  keep-history: false # always force push
  local_dir: .out
