name: "Changelog Verifier"
on:
  pull_request:
    branches: [ '**', '!feature/**' ]
    types: [opened, edited, review_requested, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  verify-changelog:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: "autocut, Skip-Changelog"
