name: Create Change Set

on:
  pull_request_target:
    types: [opened, edited]
    paths-ignore:
      - 'changelogs/fragments/**/*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update Changelog
        uses: BigSamu/OpenSearch_Change_Set_Create_Action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changeset_token: ${{ secrets.CHANGESET_TOKEN }}
          changeset_path: changelogs/fragments
